<a href="https://colab.research.google.com/github/YashRaj-I/py/blob/master/PyTorch_0_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('hello i am learning deep learning')

hello i am learning deep learning


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import torch
print(torch.__version__)

2.5.1+cu124


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
scalar =torch.tensor(8)
scalar

tensor(8)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.shape

torch.Size([])

In [ ]:
martix =torch.tensor([[1,2],[3,4]])
martix

tensor([[1, 2],
        [3, 4]])

In [ ]:
martix.ndim

2

In [ ]:
martix.shape

torch.Size([2, 2])

In [ ]:
martix[0]

tensor([1, 2])

In [ ]:
Tensor =torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
Tensor.ndim

3

In [ ]:
Tensor.shape

torch.Size([1, 3, 3])

**lets create random tensor**

In [ ]:
random_tensor =torch.rand(3,4)
random_tensor

tensor([[0.8415, 0.8955, 0.2252, 0.4380],
        [0.6963, 0.6718, 0.1503, 0.4281],
        [0.4383, 0.0649, 0.7629, 0.9250]])

In [ ]:
random_tensor.ndim

2

**Create a random tensor with similar shape to an image tensor**

In [ ]:
random_image_size_tensor =torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

**Create a tensor of all zeros**

In [ ]:
tensor_zeros =torch.zeros(size=(3,4))
tensor_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

**Create a tensor with all ones**

In [ ]:
tensor_ones =torch.ones(size=(3,4))
tensor_ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

**Create a range and tensor like**

In [ ]:
tensor_range = torch.range(1,11)
tensor_range

<ipython-input-54-cd374feab858>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  tensor_range = torch.range(1,11)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
tensor_arange = torch.arange(start=1,end=11,step=1)
tensor_arange

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**# Can also create a tensor of zeros similar to another tensor**


In [ ]:
tensor_zeros =torch.zeros_like(input=tensor_arange)
tensor_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Let's see how to create some tensors with specific datatypes. We can do so using the dtype parameter.**

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations perfromed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

**Manipulating tensors (tensor operations)**

In [ ]:
some_tensor = torch.tensor([1,2,3])
some_tensor

tensor([1, 2, 3])

In [ ]:
some_tensor +10

tensor([11, 12, 13])

In [ ]:
some_tensor-10

tensor([-9, -8, -7])

In [ ]:
some_tensor*10

tensor([10, 20, 30])

In [ ]:
some_tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
torch.mul(some_tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(some_tensor,10)

tensor([11, 12, 13])

In [ ]:
# Element-wise matrix multiplication

print(some_tensor, "*", some_tensor)
print("Equals:", some_tensor * some_tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(some_tensor,some_tensor)

tensor(14)

In [ ]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
some_tensor @ some_tensor

tensor(14)

# One of the most common errors in deep learning (shape errors)

In [ ]:
tensor_A = torch.tensor([[1, 2],
                      [3, 4],
                      [5, 6]])
tensor_B  = torch.tensor([[7, 10],
                      [8, 11],
                      [9, 12]])
# You can also use torch.mm() which is a short for torch.matmul().
# torch.mm(tensor_A, tensor_B) #this shows error because of their inner dimensions match.

# we need to transpose one matrix


In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_A @ tensor_B.T

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

# Finding the min, max, mean, sum, etc (aggregation)

In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# finding min
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
# finding max
torch.max(x),x.max()

(tensor(90), tensor(90))

In [ ]:
# finding meam
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()


(tensor(45.), tensor(45.))

In [ ]:
# finding sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

 # Positional min/max


In [ ]:
# create a tensor
tensor = torch.arange(10,100,10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")



Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


# Reshaping, stacking, squeezing and unsqueezing

In [ ]:
a = torch.arange(1., 9.)
a, a.shape ,a.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]), 1)

# RESHAPING

In [ ]:
a_reshaped = a.reshape(2,4)
a_reshaped, a_reshaped.shape ,a_reshaped.ndim

(tensor([[1., 2., 3., 4.],
         [5., 6., 7., 8.]]),
 torch.Size([2, 4]),
 2)

In [ ]:
x = torch.arange(1, 10)  # Tensor: [1, 2, 3, 4, 5, 6, 7, 8, 9]
x_reshaped = x.reshape(1,9)  # Reshape to 3x3 matrix
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

# VIEW

In [ ]:
x1 = torch.arange(1., 8.)
x_view = x1.view(1,7)
x1,x_view, x_view.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]),
 tensor([[1., 2., 3., 4., 5., 6., 7.]]),
 torch.Size([1, 7]))

In [ ]:
# change x_view, changes x
x_view[:,0] = 5
x_view, x1

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

# **STACKED**

In [ ]:
x_stacked= torch.stack([x,x,x,x],dim=0) # Stacks tensors vertically
x_stacked

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

# **squeeze**

In [ ]:
# To do so you can use torch.squeeze()
# (I remember this as squeezing the tensor to only have dimensions over 1).
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])


# **unsqueeze**

In [ ]:
# you can use torch.unsqueeze() to add a dimension value of 1 at a specific index.

In [ ]:
print(f"New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


New tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])

New tensor: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])


# **Permuting**

In [ ]:
x = torch.rand(2,5,7)
x.shape,x.permute(2,0,1).shape

(torch.Size([2, 5, 7]), torch.Size([7, 2, 5]))

# **Indexing (selecting data from tensors)**

In [ ]:
y =torch.arange(1,10).reshape(1,3,3)
y

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# Let's index bracket by bracket
print(f"First square bracket :\n{y[0]}")
print(f"Second square bracket : {y[0][0]}")
print(f"Third square bracket : {y[0][0][0]}")

First square bracket :
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket : tensor([1, 2, 3])
Third square bracket : 1


In [ ]:
# Get all values of 0th dimension and the 0 index of 1st dimension
y[:,0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
y[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
y[:,1,1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
y[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

# **NUMY AND PYTORCH TENSOR**

In [ ]:
# torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.

import torch
import numpy as np
array = np.arange(1.0,10.0)
tensor = torch.from_numpy(array)
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [ ]:
array = array + 1
array, tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [ ]:
# tensor.numpy() - PyTorch tensor -> NumPy array.
tensor1 =torch.ones(5)
tensor_numpy = tensor1.numpy()
tensor_numpy, tensor



(array([1., 1., 1., 1., 1.], dtype=float32), tensor([1., 1., 1., 1., 1.]))

In [ ]:
tensor1 = tensor1 + 1
tensor1, tensor_numpy

(tensor([2., 2., 2., 2., 2.]), array([1., 1., 1., 1., 1.], dtype=float32))

# **Reproducibility (trying to take the random out of random)**

In [ ]:
import torch
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B


Tensor A:
tensor([[0.6458, 0.6157, 0.2577, 0.8374],
        [0.8000, 0.7778, 0.9073, 0.0464],
        [0.8208, 0.1826, 0.3361, 0.6272]])

Tensor B:
tensor([[0.5187, 0.7601, 0.9593, 0.6796],
        [0.2529, 0.1559, 0.5887, 0.6276],
        [0.0844, 0.7003, 0.8521, 0.7984]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
import torch

RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(seed=RANDOM_SEED)

random_tensor_D = torch.rand(3,4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [ ]:
!nvidia-smi

Thu Feb  6 15:09:01 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   50C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [ ]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

# **3. Putting tensors (and models) on the GPU**

In [ ]:
import torch
# crete a tensor
tensor = torch.tensor([1,2,3])

# tensor not on GPU
print(tensor, tensor.device)

# move on to GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

# **3. Putting tensors (and models) on the GPU**

In [ ]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

# Exercise


In [ ]:
# Create a random tensor with shape (7, 7).
import torch
tensor = torch.rand(7,7)
tensor

tensor([[0.8110, 0.6402, 0.3409, 0.9095, 0.4100, 0.8797, 0.8260],
        [0.9050, 0.5953, 0.0651, 0.4372, 0.6062, 0.6947, 0.9453],
        [0.4783, 0.9165, 0.5384, 0.4754, 0.2139, 0.7107, 0.1604],
        [0.0614, 0.2024, 0.2951, 0.7087, 0.8540, 0.1038, 0.8435],
        [0.1687, 0.6313, 0.5307, 0.2230, 0.0439, 0.4637, 0.2090],
        [0.8419, 0.9067, 0.8089, 0.7312, 0.8034, 0.8097, 0.1095],
        [0.0206, 0.0593, 0.7073, 0.8666, 0.1183, 0.0601, 0.3925]])

In [ ]:
# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)
# (hint: you may have to transpose the second tensor).
another_tensor = torch.rand(1,7)
matrix_multiplication = torch.matmul(tensor,another_tensor.T)
matrix_multiplication

tensor([[2.8372],
        [2.6652],
        [1.8523],
        [1.7884],
        [1.2563],
        [2.7095],
        [1.2083]])

In [ ]:
# Set the random seed to 0 and do exercises 2 & 3 over again.
RANDOM_SEED = 0
torch.manual_seed(seed=RANDOM_SEED)
tensor = torch.rand(7,7)

torch.manual_seed(seed=RANDOM_SEED)
another_tensor = torch.rand(1,7)

matrix_multiplication = torch.matmul(tensor,another_tensor.T)
matrix_multiplication

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [ ]:
# Speaking of random seeds, we saw how to set it with torch.manual_seed()
#  but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one).
  # If there is, set the GPU random seed to 1234.
RANDOM_SEED = 1234
torch.cuda.manual_seed(seed=RANDOM_SEED)
tensor = torch.rand(7,7)

torch.manual_seed(seed=RANDOM_SEED)
another_tensor = torch.rand(1,7)

matrix_multiplication = torch.matmul(tensor,another_tensor.T)
matrix_multiplication

tensor([[0.4845],
        [1.0341],
        [0.9063],
        [1.1373],
        [0.5184],
        [1.1923],
        [1.0276]])

In [ ]:
# Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this).
#  Set torch.manual_seed(1234) when creating the tensors
  # (this doesn't have to be the GPU random seed).
RANDOM_SEED = 1234
torch.manual_seed(seed=RANDOM_SEED)
tensor1 = torch.rand(2,3)

torch.manual_seed(seed=RANDOM_SEED)
another_tensor1 = torch.rand(2,3)

device = "cuda" if torch.cuda.is_available() else "cpu"

random_tensor1 = tensor1.to(device)
random_tensor2 = another_tensor1.T.to(device)
random_tensor1,random_tensor2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0290, 0.3666],
         [0.4019, 0.0583],
         [0.2598, 0.7006]]))

In [ ]:
# Perform a matrix multiplication on the tensors you created in 6
#  (again, you may have to adjust the shapes of one of the tensors).
multiplication = torch.matmul(random_tensor1,random_tensor2)
multiplication

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]])

In [ ]:
# Find the maximum and minimum values of the output of 7.
multiplication.min(), multiplication.max()

(tensor(0.2161), tensor(0.6287))

In [ ]:
# Find the maximum and minimum index values of the output of 7.
multiplication.argmax(), multiplication.argmin()

(tensor(3), tensor(1))

In [ ]:
# Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the
#  1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7
#  when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
RANDOM_SEED = 7
torch.manual_seed(seed=RANDOM_SEED)
tensor = torch.rand(1,1,1,10)


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [ ]:
squeezed_tensor = tensor.squeeze()
squeezed_tensor,squeezed_tensor.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))